# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from model.contact import Contact


class TestAddContact:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_add_contact(self):
        self.open_home_page()
        self.driver.set_window_size(1235, 973)
        self.login()
        self.open_contact_page()
        self.create_contact(Contact("fgh", "hfgh", "fgh", "fhfg", "hfg", "fghfg", "fghfh", "54", "546", "4864", "345343",
                            "fdgf", "gsaf", "sdfh", "gdsrg", "gdg", "gdfg", "dgdfg"))
        self.return_to_home_page()
        self.logout()

    def logout(self):
        self.driver.find_element(By.LINK_TEXT, "Logout").click()

    def return_to_home_page(self):
        self.driver.find_element(By.LINK_TEXT, "home page").click()

    def create_contact(self, contact):
        self.driver.find_element(By.NAME, "firstname").click()
        self.driver.find_element(By.NAME, "firstname").send_keys(contact.firstname)
        self.driver.find_element(By.NAME, "middlename").click()
        self.driver.find_element(By.NAME, "middlename").send_keys(contact.middlename)
        self.driver.find_element(By.NAME, "lastname").click()
        self.driver.find_element(By.NAME, "lastname").send_keys(contact.lastname)
        self.driver.find_element(By.NAME, "nickname").click()
        self.driver.find_element(By.NAME, "nickname").send_keys(contact.nickname)
        self.driver.find_element(By.NAME, "title").click()
        self.driver.find_element(By.NAME, "title").send_keys(contact.title)
        self.driver.find_element(By.NAME, "company").click()
        self.driver.find_element(By.NAME, "company").send_keys(contact.company)
        self.driver.find_element(By.NAME, "address").click()
        self.driver.find_element(By.NAME, "address").send_keys(contact.address)
        self.driver.find_element(By.NAME, "home").click()
        self.driver.find_element(By.NAME, "home").send_keys(contact.home)
        self.driver.find_element(By.NAME, "mobile").click()
        self.driver.find_element(By.NAME, "mobile").send_keys(contact.mobile)
        self.driver.find_element(By.NAME, "work").click()
        self.driver.find_element(By.NAME, "work").send_keys(contact.work)
        self.driver.find_element(By.NAME, "fax").click()
        self.driver.find_element(By.NAME, "fax").send_keys(contact.fax)
        self.driver.find_element(By.NAME, "email").click()
        self.driver.find_element(By.NAME, "email").send_keys(contact.email)
        self.driver.find_element(By.NAME, "email2").click()
        self.driver.find_element(By.NAME, "email2").send_keys(contact.email2)
        self.driver.find_element(By.NAME, "email3").click()
        self.driver.find_element(By.NAME, "email3").send_keys(contact.email3)
        self.driver.find_element(By.NAME, "homepage").click()
        element = self.driver.find_element(By.NAME, "homepage")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.NAME, "homepage").send_keys(contact.homepage)
        self.driver.find_element(By.NAME, "bday").click()
        dropdown = self.driver.find_element(By.NAME, "bday")
        dropdown.find_element(By.XPATH, "//option[. = '16']").click()
        self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(61) > option:nth-child(18)").click()
        self.driver.find_element(By.NAME, "bmonth").click()
        dropdown = self.driver.find_element(By.NAME, "bmonth")
        dropdown.find_element(By.XPATH, "//option[. = 'January']").click()
        self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(62) > option:nth-child(2)").click()
        self.driver.find_element(By.NAME, "byear").click()
        self.driver.find_element(By.NAME, "byear").send_keys("6464")
        self.driver.find_element(By.NAME, "aday").click()
        dropdown = self.driver.find_element(By.NAME, "aday")
        dropdown.find_element(By.XPATH, "//option[. = '18']").click()
        self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(66) > option:nth-child(20)").click()
        self.driver.find_element(By.NAME, "amonth").click()
        dropdown = self.driver.find_element(By.NAME, "amonth")
        dropdown.find_element(By.XPATH, "//option[. = 'January']").click()
        self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(67) > option:nth-child(2)").click()
        self.driver.find_element(By.NAME, "ayear").click()
        self.driver.find_element(By.NAME, "ayear").send_keys("5444")
        self.driver.find_element(By.NAME, "new_group").click()
        dropdown = self.driver.find_element(By.NAME, "new_group")
        dropdown.find_element(By.XPATH, "//option[. = 'dfg']").click()
        self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(71) > option:nth-child(6)").click()
        self.driver.find_element(By.NAME, "address2").click()
        self.driver.find_element(By.NAME, "address2").send_keys(contact.address2)
        self.driver.find_element(By.NAME, "phone2").click()
        self.driver.find_element(By.NAME, "phone2").send_keys(contact.phone2)
        self.driver.find_element(By.NAME, "notes").click()
        self.driver.find_element(By.NAME, "notes").send_keys(contact.notes)
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(87)").click()

    def open_contact_page(self):
        self.driver.find_element(By.LINK_TEXT, "add new").click()

    def login(self):
        self.driver.find_element(By.NAME, "user").send_keys("admin")
        self.driver.find_element(By.NAME, "pass").click()
        self.driver.find_element(By.NAME, "pass").send_keys("secret")
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()

    def open_home_page(self):
        self.driver.get("http://localhost/addressbook/")
