# Generated by Selenium IDE

from model.contact import Contact


def test_add_contact(app):
    app.contact.create_contact(Contact("fgh", "hfgh", "fgh", "fhfg", "hfg", "fghfg", "fghfh", "54", "546", "4864", "345343",
                            "fdgf", "gsaf", "sdfh", "gdsrg", "gdg", "gdfg", "dgdfg"))

