# Generated by Selenium IDE

from model.group import Group


def test_add_group(app):
    app.group.create(Group(name="dfg", header="fhf", footer="rde"))


def test_add_empty_group(app):
    app.group.create(Group(name="", header="", footer=""))
